// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"examples.mdx": () => import("../content/docs/examples.mdx?collection=docs"), "first-app.mdx": () => import("../content/docs/first-app.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "components/input.mdx": () => import("../content/docs/components/input.mdx?collection=docs"), "components/layout.mdx": () => import("../content/docs/components/layout.mdx?collection=docs"), "components/overlays.mdx": () => import("../content/docs/components/overlays.mdx?collection=docs"), "components/scrolling.mdx": () => import("../content/docs/components/scrolling.mdx?collection=docs"), "components/terminal.mdx": () => import("../content/docs/components/terminal.mdx?collection=docs"), "components/text.mdx": () => import("../content/docs/components/text.mdx?collection=docs"), "fundamentals/building-uis.mdx": () => import("../content/docs/fundamentals/building-uis.mdx?collection=docs"), "fundamentals/components.mdx": () => import("../content/docs/fundamentals/components.mdx?collection=docs"), "fundamentals/hot-reload.mdx": () => import("../content/docs/fundamentals/hot-reload.mdx?collection=docs"), "fundamentals/state.mdx": () => import("../content/docs/fundamentals/state.mdx?collection=docs"), "interactivity/focus.mdx": () => import("../content/docs/interactivity/focus.mdx?collection=docs"), "interactivity/keyboard.mdx": () => import("../content/docs/interactivity/keyboard.mdx?collection=docs"), "interactivity/mouse.mdx": () => import("../content/docs/interactivity/mouse.mdx?collection=docs"), "terminal-concepts/ansi.mdx": () => import("../content/docs/terminal-concepts/ansi.mdx?collection=docs"), "terminal-concepts/how-terminals-work.mdx": () => import("../content/docs/terminal-concepts/how-terminals-work.mdx?collection=docs"), "terminal-concepts/limitations.mdx": () => import("../content/docs/terminal-concepts/limitations.mdx?collection=docs"), "testing/basics.mdx": () => import("../content/docs/testing/basics.mdx?collection=docs"), "testing/matchers.mdx": () => import("../content/docs/testing/matchers.mdx?collection=docs"), "testing/visual.mdx": () => import("../content/docs/testing/visual.mdx?collection=docs"), }),
};
export default browserCollections;